name: random reviewers

on:
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  add_reviewers:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
      ACTIONS_RUNNER_DEBUG: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: generate_reviewers
        id: generate_reviewers
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const team = ["griiim134", "Eu4ng", "Noong2", "workminkyoung"];
            const candidate = team.filter((e) => e != "${{ github.event.pull_request.user.login }}");
            const shuffled = candidate.sort(() => 0.5 - Math.random());
            const reviewers = shuffled.slice(0, 2);
            const comment = `@${reviewers.join(' & @')}님 리뷰 부탁드립니다.`;
            core.setOutput("comment", comment);
            core.setOutput("reviewers", reviewers.join(', '));
      - name: coment PR
        uses: github-actions-up-and-running/pr-comment@v1.0.1
        with:
          message: ${{ steps.generate_reviewers.outputs.comment }}
          repo-token: ${{ secrets.TOKEN }}
      - name: add_reviewers
        uses: Madrapps/add-reviewers@v1
        with:
          reviewers: ${{ steps.generate_reviewer.outputs.reviewers }}
          token: ${{ secrets.TOKEN }}
